TRUNCATE TABLE gbb_gdiof_dafor;
INSERT INTO  `bb`.`gbb_gdiof_dafor` SELECT * FROM  `gbbdr`.`gbb_gdiof_dafor` ;
TRUNCATE TABLE gbb_file;
INSERT INTO  `bb`.`gbb_file` SELECT * FROM  `gbbdr`.`gbb_file` ;
TRUNCATE TABLE gbb_gmodu_plus;
INSERT INTO  `bb`.`gbb_gmodu_plus` SELECT * FROM  `gbbdr`.`gbb_gmodu_plus` ;
TRUNCATE TABLE gbb_gmodu_taxonomy;
INSERT INTO  `bb`.`gbb_gmodu_taxonomy` SELECT * FROM  `gbbdr`.`gbb_gmodu_taxonomy` ;
TRUNCATE TABLE gbb_gresp_dafor;
INSERT INTO  `bb`.`gbb_gresp_dafor` SELECT * FROM  `gbbdr`.`gbb_gresp_dafor` ;
TRUNCATE TABLE gbb_gresp_plus;
INSERT INTO  `bb`.`gbb_gresp_plus` SELECT * FROM  `gbbdr`.`gbb_gresp_plus` ;
TRUNCATE TABLE gbb_netab_dafor;
INSERT INTO  `bb`.`gbb_netab_dafor` SELECT * FROM  `gbbdr`.`gbb_netab_dafor` ;
TRUNCATE TABLE gbb_session;
INSERT INTO  `bb`.`gbb_session` SELECT * FROM  `gbbdr`.`gbb_session` ;
TRUNCATE TABLE taxonomy_index;
INSERT INTO  `bb`.`taxonomy_index` SELECT * FROM  `gbbdr`.`taxonomy_index` ;
TRUNCATE TABLE taxonomy_term_data;
INSERT INTO  `bb`.`taxonomy_term_data` SELECT * FROM  `gbbdr`.`taxonomy_term_data` ;
TRUNCATE TABLE taxonomy_term_hierarchy;
INSERT INTO  `bb`.`taxonomy_term_hierarchy` SELECT * FROM  `gbbdr`.`taxonomy_term_hierarchy` ;
TRUNCATE TABLE taxonomy_vocabulary;
INSERT INTO  `bb`.`taxonomy_vocabulary` SELECT * FROM  `gbbdr`.`taxonomy_vocabulary` ;
